#http://www.osgchina.org/show.php?id=46

ABI=armeabi-v7a
API=19
SYSROOT=$PWD/../build/armeabi-v7a

cmake . \
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI=$ABI \
    -DANDROID_PLATFORM=$API \
    -DANDROID_STL=c++_static \
    \
    -DDYNAMIC_OPENTHREADS=OFF \
    -DDYNAMIC_OPENSCENEGRAPH=OFF \
    \
    -DOSG_GL1_AVAILABLE=OFF \
    -DOSG_GL2_AVAILABLE=OFF \
    -DOSG_GL3_AVAILABLE=OFF \
    -DOSG_GLES1_AVAILABLE=OFF \
    -DOSG_GLES2_AVAILABLE=ON \
    -DOSG_GL_LIBRARY_STATIC=OFF \
    -DOSG_GL_DISPLAYLISTS_AVAILABLE=OFF \
    -DOSG_GL_MATRICES_AVAILABLE=OFF \
    -DOSG_GL_VERTEX_FUNCS_AVAILABLE=OFF \
    -DOSG_GL_VERTEX_ARRAY_FUNCS_AVAILABLE=OFF \
    -DOSG_GL_FIXED_FUNCTION_AVAILABLE=OFF \
    \
    -DCMAKE_INSTALL_PREFIX=$SYSROOT

make
make install
